### ISSUE TITLE
Make Popover not require a Text input field

### ISSUE THREAD

**Issue by jasondavis** [mjolnic/bootstrap-popover-picker#6]
I use the popover for selecting Milestones, Tags, and Assigned User from Userlist for a Task Management app.

I would really like to use the library on a simple `<span>` field instead of a text input.  

Basically when you open the Popover in my app, I load the data and when user selects an item I make an AJAX request to save the selected item.  I then update the DOM with the value manually in several places using the provided Events and callbacks.

For this reason, the Text Input is simply messing up the appearance of my app right now.

Hee are some example sites that use a similar style popover widget which do similar task that I am trying to do and they do not have a Text Input...

Dribbble:  
![](http://i.imgur.com/WvyhYy5.png)

GitHub Issues:  
![](http://i.imgur.com/cDP0tNA.png)

Envato Marketplace sites:  

![](http://i.imgur.com/cjQzIg0.png)

**Comment by jasondavis** [comment]
I would be very appreciative of any help with this modification.  I could simply make the Text input hidden but then I am not sure if I would be able to trigger the popover to open/close or not.

I plan on making a selector/picker out of this for `Task Milestones`, `Assigned User` which will show a thumbnail image and name of all users.  And `Project Tags`

**Comment by mjolnic** [comment]
Hi @jasondavis maybe is not very clear in the docs, but you can actually use the plugin without an actual input, simply change the input selector in the plugin options like in this demo I created: http://jsfiddle.net/mjolnic/cw5eLpvf/

I know that this may be confusing but I will upgrade it in the next commits
Thx

**Comment by jasondavis** [comment]
Thanks a bunch!  BTW even though this is closed...I added a new example image at the bottom of my post above for Gmail Labels.  Might be inspiration for other using this library thanks again

**Comment by jasondavis** [comment]
All that fussing and in the end I think I am actually going to use a text input anyways!  Thanks for showing the alternative way though i'm sure it will come in handy later and for others too!

If you're interested in seeing how I put your popover to use for MIlestones, here is a screenshot...

It saves MIlestones ID to Task record database with AJAX on Selection.  

Selecting "None" clears any previous saved value.  

In addition to my **Milestone Picker/Selector/Manager** I plan to do similar for:  
 - **Assigned User** with user thumbnail images  
 - one for **Task Tags** which will allow to select multiple tags for a Project Task.  

I'm really excited about finding your library for my project as it is the perfect starting point to build these widgets!  

http://i.imgur.com/Iv8gGOW.png
![iv8ggow 1](https://cloud.githubusercontent.com/assets/186818/8313321/fe60ad8e-19af-11e5-9cf9-5e51253e0235.png)
